# Generated by Django 4.1.7 on 2023-05-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment_text',
            new_name='comment_text',
        ),
    ]
